"""
Gitignore completeness check for init.

WHAT: Verifies .gitignore contains expected patterns for the project's tech stack
and OS globals, using vendored templates from github/gitignore.

WHY: Incomplete .gitignore files let OS artifacts (.DS_Store), build outputs, and
environment files slip into repos. Agents don't know what's missing — they need
a reference set.

FIX: Appends missing patterns in a "# Added by agent-harness" block. Never removes
or reorders existing lines.
"""

from __future__ import annotations

from pathlib import Path

from agent_harness.setup import SetupIssue

_TEMPLATES_DIR = (
    Path(__file__).resolve().parent.parent.parent / "templates" / "gitignore"
)

_STACK_TEMPLATES: dict[str, str] = {
    "python": "Python.gitignore",
    "javascript": "Node.gitignore",
}

_OS_TEMPLATES = ["macOS.gitignore", "Windows.gitignore", "Linux.gitignore"]


def _parse_patterns(text: str) -> set[str]:
    """Extract non-comment, non-blank lines from gitignore content."""
    patterns = set()
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            patterns.add(stripped)
    return patterns


def _load_template(name: str) -> set[str]:
    """Load patterns from a vendored template file."""
    path = _TEMPLATES_DIR / name
    if not path.exists():
        return set()
    return _parse_patterns(path.read_text())


def _load_expected_patterns(stacks: set[str]) -> set[str]:
    """Load all expected patterns for given stacks + OS globals."""
    patterns: set[str] = set()
    for os_template in _OS_TEMPLATES:
        patterns |= _load_template(os_template)
    for stack in stacks:
        template_name = _STACK_TEMPLATES.get(stack)
        if template_name:
            patterns |= _load_template(template_name)
    return patterns


def check_gitignore_setup(project_dir: Path, stacks: set[str]) -> list[SetupIssue]:
    """Check .gitignore completeness against vendored templates."""
    gitignore_path = project_dir / ".gitignore"
    expected = _load_expected_patterns(stacks)

    if not gitignore_path.exists():

        def fix_create(p: Path) -> None:
            content = "# Generated by agent-harness\n"
            for os_template in _OS_TEMPLATES:
                content += f"\n# {os_template}\n"
                path = _TEMPLATES_DIR / os_template
                if path.exists():
                    content += path.read_text().rstrip() + "\n"
            for stack in sorted(stacks):
                template_name = _STACK_TEMPLATES.get(stack)
                if template_name:
                    content += f"\n# {template_name}\n"
                    path = _TEMPLATES_DIR / template_name
                    if path.exists():
                        content += path.read_text().rstrip() + "\n"
            (p / ".gitignore").write_text(content)

        return [
            SetupIssue(
                file=".gitignore",
                message="No .gitignore found — will create from templates",
                severity="critical",
                fix=fix_create,
            )
        ]

    existing = _parse_patterns(gitignore_path.read_text())
    missing = expected - existing

    if not missing:
        return []

    missing_display = ", ".join(sorted(missing)[:30])
    more = f" (+{len(missing) - 30} more)" if len(missing) > 30 else ""

    def fix_append(p: Path) -> None:
        gitignore = p / ".gitignore"
        current = gitignore.read_text()
        if not current.endswith("\n"):
            current += "\n"
        block = "\n# Added by agent-harness\n"
        for pattern in sorted(missing):
            block += pattern + "\n"
        gitignore.write_text(current + block)

    return [
        SetupIssue(
            file=".gitignore",
            message=f"Missing {len(missing)} patterns: {missing_display}{more}",
            severity="critical",
            fix=fix_append,
        )
    ]
